export enum RolePrevileges {
  ALL_STAFF_OPERATIONS,
  ADD_STAFF,
  READ_STAFF,
  UPDATE_STAFF,
  DELETE_STAFF,
  // PRODUCT
  ALL_PRODUCT_OPERATIONS,
  ADD_PRODUCT,
  READ_PRODUCT,
  UPDATE_PRODUCT,
  DELETE_PRODUCT,
  // CATEGORY
  ALL_CATEGORY_OPERATIONS,
  ADD_CATEGORY,
  READ_CATEGORY,
  UPDATE_CATEGORY,
  DELETE_CATEGORY,
  // CUSTOMER
  ALL_CUSTOMER_OPERATIONS,
  ADD_CUSTOMER,
  READ_CUSTOMER,
  UPDATE_CUSTOMER,
  DELETE_CUSTOMER,
  // SALE
  ALL_SALE_OPERATIONS,
  ADD_SALE,
  READ_SALE,
  UPDATE_SALE,
  DELETE_SALE,
  // WAREHOUSE
  ALL_WAREHOUSE_OPERATIONS,
  ADD_WAREHOUSE,
  READ_WAREHOUSE,
  UPDATE_WAREHOUSE,
  DELETE_WAREHOUSE,
  // SUPPLY
  ALL_SUPPLY_OPERATIONS,
  ADD_SUPPLY,
  READ_SUPPLY,
  UPDATE_SUPPLY,
  DELETE_SUPPLY,
  //  ######### SUBSCRIPTIONS
  // # SALES
  LISTEN_ADD_SALE,
  LISTEN_EDIT_SALE,
  LISTEN_DELETE_SALE,
  // #PRODUCT
  LISTEN_ADD_PRODUCT,
  LISTEN_EDIT_PRODUCT,
  LISTEN_DELETE_PRODUCT,
  // #STAFF
  LISTEN_ADD_STAFF,
  LISTEN_DELETE_STAFF,
  // #SUPPLY
  LISTEN_ADD_SUPPLY,
  LISTEN_EDIT_SUPPLY,
  LISTEN_DELETE_SUPPLY,
  // #CATEGORY
  LISTEN_ADD_CATEGORY,
  LISTEN_EDIT_CATEGORY,
  LISTEN_DELETE_CATEGORY,
  // #WAREHOUSE
  LISTEN_ADD_WAREHOUSE,
  LISTEN_EDIT_WAREHOUSE,
  LISTEN_DELETE_WAREHOUSE,
  // #########END SUBSCRIPTION
  // ENTERPRISE
  ADD_ENTERPRISE,
  UPDATE_ENTERPRISE,
  // SYSTEM
  INITIALIZED_SYSTEM,
}
